#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin.
# Build: compile src/ → lib/ with the dsh checkout's tsc.
# Requires DSH_CHECKOUT pointing at a dsh source checkout (auto-probe below).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# DSH_CHECKOUT 探测：环境变量 → 常见路径（home 下 dsh-harness）
CHECKOUT="${DSH_CHECKOUT:-}"
if [ -z "$CHECKOUT" ]; then
  for candidate in "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness"; do
    if [ -d "$candidate/packages" ]; then CHECKOUT="$candidate"; break; fi
  done
fi
if [ -z "$CHECKOUT" ] || [ ! -d "$CHECKOUT/packages" ]; then
  echo "build: cannot locate the dsh checkout (set DSH_CHECKOUT)" >&2
  exit 1
fi

TSC="$CHECKOUT/node_modules/.bin/tsc"
if [ ! -x "$TSC" ] && [ ! -f "$TSC.cmd" ]; then
  echo "build: tsc not found at $TSC" >&2
  exit 1
fi

link_pkg() {
  local target="$CHECKOUT/$2"
  if [ ! -e "$target" ]; then
    echo "build: dependency target missing: $target" >&2
    exit 1
  fi
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = path.resolve(process.argv[2]);
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "node_modules/$1" "$target"
}

echo "=== Linking build dependencies (checkout: $CHECKOUT) ==="
mkdir -p node_modules/@deepseek-ai
node -e "const fs=require('fs');fs.rmSync('node_modules/@standard-schema',{recursive:true,force:true})"
link_pkg cordis vendor/cordis
link_pkg cosmokit vendor/cosmokit
link_pkg schemastery vendor/schemastery
link_pkg @deepseek-ai/dsh-tools packages/core/tools
# 本插件不引用 dsh-llm / system-prompt（精简 checkout 无此目录），按需再启用：
# link_pkg @deepseek-ai/dsh-llm packages/llm/llm
# link_pkg @deepseek-ai/dsh-system-prompt packages/core/system-prompt
# @types/node（编译类型；checkout 自带）
link_pkg @types/node node_modules/@types/node

STD_SCHEMA=""
if [ -d "$CHECKOUT/node_modules/.pnpm" ]; then
  STD_SCHEMA=$(find "$CHECKOUT/node_modules/.pnpm" -maxdepth 1 -type d -iname '@standard-schema+spec@*' 2>/dev/null | head -1 || true)
fi
if [ -n "$STD_SCHEMA" ]; then
  node -e "
    const fs = require('fs');
    const path = require('path');
    fs.rmSync('node_modules/@standard-schema', { recursive: true, force: true });
    fs.mkdirSync('node_modules/@standard-schema', { recursive: true });
    fs.symlinkSync(path.resolve(process.argv[1]), path.resolve('node_modules/@standard-schema/spec'), process.platform === 'win32' ? 'junction' : 'dir');
  " "$STD_SCHEMA/node_modules/@standard-schema/spec"
fi

echo "=== Compiling src → lib ==="
"$TSC" -p tsconfig.json

# ── 浏览器侧（UI 按钮 + 面板）────────────────────────────────────────────
# 精简 checkout 没有 react / client 包 / tsdown，从同机 ensemble 插件那份完整
# pnpm store 借用（与 dsh-self-verifier 的构建做法一致）。
ENSEMBLE="${ENSEMBLE:-E:/dsh/dsh-model-ensemble/node_modules}"
if [ -d "$ENSEMBLE/.bin" ]; then
  echo "=== Linking client dependencies (store: $ENSEMBLE) ==="
  link_abs() {
    local target="$2"
    if [ ! -e "$target" ]; then echo "build: client dep missing: $target (skipped)" >&2; return 0; fi
    node -e "
      const fs = require('fs');
      const path = require('path');
      const link = path.resolve(process.argv[1]);
      const target = path.resolve(process.argv[2]);
      fs.rmSync(link, { recursive: true, force: true });
      fs.mkdirSync(path.dirname(link), { recursive: true });
      fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
    " "node_modules/$1" "$target"
  }
  link_abs react "$ENSEMBLE/react"
  link_abs @types/react "$ENSEMBLE/@types/react"
  link_abs @deepseek-ai/cordis "$ENSEMBLE/@deepseek-ai/cordis"
  link_abs @deepseek-ai/dsh-client-runtime "$ENSEMBLE/@deepseek-ai/dsh-client-runtime"
  link_abs @deepseek-ai/dsh-client-ui-slots "$ENSEMBLE/@deepseek-ai/dsh-client-ui-slots"
  link_abs @deepseek-ai/dsh-client-ui-conversation "$ENSEMBLE/@deepseek-ai/dsh-client-ui-conversation"

  echo "=== Typecheck client (non-fatal) ==="
  "$TSC" -p tsconfig.client.json --noEmit || echo "build: client typecheck reported issues (continuing)"

  echo "=== Bundling client → lib/client.js (tsdown) ==="
  "$ENSEMBLE/.bin/tsdown"
else
  echo "build: no client dependency store at $ENSEMBLE — skipping client bundle" >&2
fi
echo "=== Build complete ==="
